name: tests

on:
  push:
    branches:
      - master
  pull_request: null

env:
  PY_COLORS: "1"

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.8"
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest
          miniforge-variant: Mambaforge

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          mamba install des-easyaccess pytest fitsio==1.0.5 cx_Oracle==8.0.1 pytables
          conda uninstall --force des-easyaccess
          python -m pip install --no-deps -e .

      - name: test
        shell: bash -l {0}
        run: |
          echo "
          [db-dessci]
          user = blah
          passwd = blahblah
          name = dessci
          server = desdb-sci.ncsa.illinois.edu
          port = 1521
          " > ~/.desservices.ini
          cat ~/.desservices.ini
          pytest -vv tests
